// Auto-generated by AndroVoid2D.

function MainApp(props) {
    return (
        <div id="app_objects">
            <img src="ball.png" style={{width: 150, height: 150, position: 'absolute', top: 5, left: 5}} />
            <img src="ball.png" style={{width: 150, height: 150, position: 'absolute', top: 50, left: 50}} />
        </div>
    );
}

const appRoot = ReactDOM.createRoot(document.getElementById("app_root"));
appRoot.render(<MainApp/>);
