// Auto-generated by AndroVoid2D.

function MainApp(props) {
    return (
        <div id="app_objects">
            @APPCODE
        </div>
    );
}

const appRoot = ReactDOM.createRoot(document.getElementById("app_root"));
appRoot.render(<MainApp/>);


